Task.create(name: 'Get rich quick')
Task.create(name: 'Buy puppy')
Task.create(name: 'Write a book')
Task.create(name: 'Make money')
Task.create(name: 'Become smart')
Task.create(name: 'Buy weed')
Task.create(name: 'Buy stingray blocker')
Task.create(name: 'Pretend to be smart')